export const ASSETS = {
  logo: "/brand/logo.svg",
  logoPng: "/brand/logo.png",
  icons: {
    alvo: "/brand/icons/alvo.png",
    ambiente: "/brand/icons/ambiente.png",
    atendimento: "/brand/icons/atendimento.png",
    calendario: "/brand/icons/calendario.png",
    conversas: "/brand/icons/conversas.png",
    correto: "/brand/icons/correto.png",
    estrela: "/brand/icons/estrela.png",
    livro: "/brand/icons/livro.png",
    local: "/brand/icons/local.png",
    pessoas: "/brand/icons/pessoas.png",
    rede: "/brand/icons/rede.png",
    resultados: "/brand/icons/resultados.png",
    shield: "/brand/icons/shield.png",
    telefone: "/brand/icons/telefone.png",
    whatsapp: "/brand/icons/whatsapp.png",
    play: "/brand/icons/play.svg",
    plus: "/brand/icons/plus.svg",
    star: "/brand/icons/star.svg",
    divisor: "/brand/icons/divisor.svg",
    corretoSvg: "/brand/icons/correto.svg",
  },
  photos: {
    heroHome: "/brand/photos/hero-home.png",
    ctaFinalAluno: "/brand/photos/cta-final-aluno.png",
    bgCta: "/brand/photos/bg-cta.png",
    ornamentLeft: "/brand/photos/ornament-flor-left.png",
    ornamentRight: "/brand/photos/ornament-flor-right.png",
    estudante: "/brand/photos/estudante.png",
    grupoCasual: "/brand/photos/grupo-casual.png",
    depoimentos: [
      "/brand/photos/depoimento-1.png",
      "/brand/photos/depoimento-2.png",
      "/brand/photos/depoimento-3.png",
      "/brand/photos/depoimento-4.png",
    ],
    comunidade: [
      "/brand/photos/comunidade-1.jpg",
      "/brand/photos/comunidade-2.jpg",
      "/brand/photos/comunidade-3.jpg",
    ],
    cursos: {
      business: "/brand/photos/cursos/business.png",
      geral: "/brand/photos/cursos/geral.png",
      viagens: "/brand/photos/cursos/viagens.png",
      empresas: "/brand/photos/cursos/empresas.png",
      particulares: "/brand/photos/cursos/particulares.png",
      online: "/brand/photos/cursos/online.png",
    },
  },
};
