export const ASSETS = {
  logo: "/brand/logo.png",
  logoPng: "/brand/logo.png",
  icons: {
    // versões para fundo claro (navy outline + acentos)
    alvo: "/brand/icons/alvo.png",
    ambiente: "/brand/icons/ambiente.png",
    atendimento: "/brand/icons/atendimento.png",
    calendario: "/brand/icons/calendario.png",
    conversas: "/brand/icons/conversas.png",
    correto: "/brand/icons/correto.png",
    estrela: "/brand/icons/estrela.png",
    livro: "/brand/icons/livro.png",
    local: "/brand/icons/local.png",
    pessoas: "/brand/icons/pessoas.png",
    rede: "/brand/icons/rede.png",
    resultados: "/brand/icons/resultados.png",
    shield: "/brand/icons/shield.png",
    telefone: "/brand/icons/telefone.png",
    whatsapp: "/brand/icons/whatsapp.png",
    // SVGs UI
    play: "/brand/icons/play.svg",
    plus: "/brand/icons/plus.svg",
    star: "/brand/icons/star.svg",
    divisor: "/brand/icons/divisor.svg",
    corretoSvg: "/brand/icons/correto.svg",
  },
  iconsWhite: {
    // versões para fundo escuro (white outline + acentos vermelho/navy)
    alvo: "/brand/icons/alvo-white.png",
    ambiente: "/brand/icons/ambiente-white.png",
    atendimento: "/brand/icons/atendimento-white.png",
    conversas: "/brand/icons/conversas-white.png",
    estrela: "/brand/icons/estrela-white.png",
    local: "/brand/icons/local-white.png",
    pessoas: "/brand/icons/pessoas-white.png",
    resultados: "/brand/icons/resultados-white.png",
    shield: "/brand/icons/shield-white.png",
    whatsapp: "/brand/icons/whatsapp-white.png",
  },
  certifications: {
    toefl: "/brand/certifications/toefl.svg",
    toeic: "/brand/certifications/toeic.png",
  },
  photos: {
    heroHome: "/brand/photos/hero-home.png",
    ctaFinalAluno: "/brand/photos/cta-final-aluno.png",
    bgCta: "/brand/photos/bg-cta.png",
    ornamentLeft: "/brand/photos/ornament-flor-left.png",
    ornamentRight: "/brand/photos/ornament-flor-right.png",
    estudante: "/brand/photos/escola-estudante.jpg",
    grupoCasual: "/brand/photos/grupo-casual.png",
    depoimentos: [
      "/brand/photos/depoimento-1.png",
      "/brand/photos/escola-1.jpg",
      "/brand/photos/escola-2.jpg",
      "/brand/photos/escola-3.jpg",
    ],
    comunidade: [
      "/brand/photos/comunidade-1.jpg",
      "/brand/photos/comunidade-2.jpg",
      "/brand/photos/comunidade-3.jpg",
    ],
    galeria: [
      "/brand/photos/galeria/galeria-01.jpg",
      "/brand/photos/galeria/galeria-02.jpg",
      "/brand/photos/galeria/galeria-03.jpg",
      "/brand/photos/galeria/galeria-04.jpg",
      "/brand/photos/galeria/galeria-05.jpg",
      "/brand/photos/galeria/galeria-06.jpg",
      "/brand/photos/galeria/galeria-07.jpg",
      "/brand/photos/galeria/galeria-08.jpg",
      "/brand/photos/galeria/galeria-09.jpg",
      "/brand/photos/galeria/galeria-10.jpg",
    ],
    cursos: {
      business: "/brand/photos/cursos/business.png",
      geral: "/brand/photos/cursos/geral.png",
      viagens: "/brand/photos/cursos/viagens.png",
      empresas: "/brand/photos/cursos/empresas.png",
      particulares: "/brand/photos/cursos/particulares.png",
      online: "/brand/photos/cursos/online.png",
    },
  },
};
