export const ASSETS = {
  logo: "/brand/logo.svg",
  logoPng: "/brand/logo.png",
  logoBg: "/brand/logo-bg.jpg",
  icons: {
    alvo: "/brand/icons/alvo.png",
    calendario: "/brand/icons/calendario.png",
    conversas: "/brand/icons/conversas.png",
    estrela: "/brand/icons/estrela.png",
    livro: "/brand/icons/livro.png",
    local: "/brand/icons/local.png",
    pessoas: "/brand/icons/pessoas.png",
    rede: "/brand/icons/rede.png",
    shield: "/brand/icons/shield.png",
    whatsapp: "/brand/icons/whatsapp.png",
  },
  photos: {
    heroHome: "/brand/photos/hero-home.png",
    estudante: "/brand/photos/estudante.png",
    grupoCasual: "/brand/photos/grupo-casual.png",
    depoimentos: [
      "/brand/photos/depoimento-1.png",
      "/brand/photos/depoimento-2.png",
      "/brand/photos/depoimento-3.png",
      "/brand/photos/depoimento-4.png",
    ],
    comunidade: [
      "/brand/photos/comunidade-1.png",
      "/brand/photos/comunidade-2.png",
      "/brand/photos/comunidade-3.png",
    ],
    ctaFinalAluno: "/brand/photos/cta-final-aluno.png",
    cursos: {
      viagens: "/brand/photos/cursos/viagens.png",
      business: "/brand/photos/cursos/business.png",
      online: "/brand/photos/cursos/online.png",
      empresas: "/brand/photos/cursos/empresas.png",
      particulares: "/brand/photos/cursos/particulares.png",
      iniciantes: "/brand/photos/cursos/iniciantes.png",
      intermediarioAvancado: "/brand/photos/cursos/intermediario-avancado.png",
      preparatorios: "/brand/photos/cursos/preparatorios.png",
    },
  },
};
